<h4>
    工程五館(資工系館)
</h4>
<p>
    你是否也有那麼一份衝動?
</p>
<p>
    想要知道自己手上那聰明到不能再聰明的手機是從哪裡誕生的
</p>
<p>
    想要知道自己現在每天離不開的電腦其中的玄妙
</p>
<p>
    想要知道神秘的程式中有什麼樣的秘密
</p>
<p>
    來趟工程五館吧
</p>
<p>
    讓這裡的電子知識充滿你的腦中吧
</p>

<p>
    身為資工人的你
</p>
<p>
    是不是也有那麼一些時候想要離開科技
</p>
<p>
    想看看美麗的建築
</p>
<p>
    坐在優閒的沙發區來杯咖啡呢?
</p>
<p>
    來趟工程五館吧
</p>
<p>
    讓你充滿電子知識的腦袋得到放鬆吧
</p>
<hr />
<p>
    <img alt="" src="<?php echo Yii::app()->request->baseUrl; ?>/statics/documents/IMG_2441.JPG" style="width:320px;height:180px;" /><img alt="" src="<?php echo Yii::app()->request->baseUrl; ?>/statics/documents/IMG_2766.JPG" style="width:320px;height:180px;" />
</p>