<h1>
註冊程序</h1>
<p>
(一)新生應於<strong>9月14日前</strong>將下列資料(註明系別、班別、學號)交由<strong>大一班代</strong>，班代收齊後按<strong>學號</strong>排列，於<strong>9月17日</strong>統一繳至各負責單位，逾時繳交者屆時將延遲領取<strong>學生證。</strong></p>
<table border="1" cellpadding="0" cellspacing="0" width="640">
<tbody>
<tr>
<td>

<p>
對象</p>
</td>
<td>
<p>
應繳資料</p>
</td>
<td>
<p>
負責單位</p>
</td>
<td>
<p>
位置</p>
</td>
</tr>
<tr>
<td>
<p align="center">
全體大一新生</p>
</td>
<td>
<p>
高中學歷證件影本及國民身分證影本，請用釘書機訂妥，並註明於證件上註明系別、班別、學號。僑生請自行交至註冊組。</p>
</td>
<td>
<p>
教務處註冊組</p>
<p align="center">
57111～3</p>
</td>
<td>
<p>
行政大樓三樓</p>
</td>
</tr>
<tr>
<td>
<p align="center">
大一男生</p>
</td>
<td>
<p>
兵役資料表(本須知之網路表格3)及兵役證明(含身分證正反面影本或退伍令、免役證明、體位證明等)黏貼於資料表中</p>
</td>
<td>
<p>
生活輔導組</p>
<p align="center">
57221</p>
</td>
<td>
<p>
第二行政中心</p>
<p>
(舊圖)一樓</p>
</td>
</tr>
<tr>
<td rowspan="2">
<p align="center">
僑生</p>
<p align="center">
(親自繳至相關單位)</p>
</td>
<td>
<p>
1.僑生資料表</p>
<p>
2.繳交教育部入學通知書影本乙份</p>
<p>
3.二吋照片二張</p>
<p>
4.繳費單收據影本、護照、居留證影本乙份</p>
<p>
5.已領有臺灣身分證、健保卡者另須繳交影本</p>
<p>
6.健保IC卡申請表</p>
</td>
<td>
<p>
國際事務處</p>
<p align="center">
57081</p>
</td>
<td>
<p>
創新育成中心</p>
<p>
一樓</p>
</td>
</tr>
<tr>
<td>
<p>
7.繳驗畢業證書正本；繳交畢業證書影本、護</p>
<p>
照、居留證影本各乙份</p>
</td>
<td>
<p>
教務處註冊組</p>
<p align="center">
57111～3</p>
</td>
<td>
<p>
行政大樓三樓</p>
</td>
</tr>
</tbody>
</table>
<p>
(二)大一新生辦理註冊應完成下列各事項，方可視為完成註冊。</p>
<p>
1.<strong>繳費</strong></p>
<p>
2.<strong>繳交學歷及身分證件影本</strong>(詳上項說明)</p>
<p>
3.<strong>線上登錄學籍資料</strong></p>
<p>
4.<strong>參加大一新生入學輔導(中大超級新生營)</strong></p>
<p>
5.<strong>大一身心適應訓練</strong></p>
<p>
6.<strong>大一英文能力分級</strong></p>
<p>
7.<strong>大一國文寫作檢定</strong></p>
<p>
8.<strong>僑生、中文系外籍生參加大一國文中文能力分級測驗</strong></p>
<p>
9.<strong>僑生、外籍生至國際事務處及註冊組繳交資料</strong></p>
<p>
10.<strong>男生另應繳交兵役資料表</strong></p>
<p>
11.<strong>就學貸款「臺灣銀行撥款通知書第二聯</strong></p>
<p>
(三)完成上述註冊應辦事項者，可由<strong>大一班代</strong>於<strong>9月1</strong><strong>8</strong><strong>日起至21日止</strong>至<u>註冊組</u>統一領取學生證。未即時完成註冊程序者，則應於完成全部註冊程序後方可領取學生證，註冊程序最遲應於<strong>9月2</strong><strong>8</strong><strong>日</strong>前完成，否則將取消其入學資格。</p>
<p>
(四)相關問題請洽詢<strong>註冊組</strong>(分機：57111～3)</p>